export default globalStyles = {
  backgroundBoldOrange: '#FF7B0F',
  backgroundLightOrange: '#ffba82',
  backgroundLightGrey: '#d6d6d6',
  backgroundDarkGrey: '#b2b2b2',
  backgroundWhite: '#fff',
  border: '#d6d6d6',
  buttonWhite: '#fff',
  textLight: '#fff',
  textOrange: '#FF7B0F',
  textDark: '#000',
  red: '#FFB3BA',
  amber: '#FFDFBA',
  yellow: '#FFFFBA',
  green: '#BAFFC9',
  logo: '#fff',
  logoNavbar: '#000',
};
